# !/usr/bin/python
# 
# @Author: Kortez
# @Email: 595976736@qq.com

###########################
## do not edit this file ##
###########################

import sys
import Tower_of_Hanoi

def test_Tower_of_Hanoi():
    Tower_of_Hanoi.Hanoi(4, 2, 3, 1)
    answers = [(2,1),(2,3),(1,3),(2,1),(3,2),(3,1),(2,1),(2,3),(1,3),(1,2),(3,2),(1,3),(2,1),(2,3),(1,3)]
    for output, ans in zip(Tower_of_Hanoi.outputs, answers):
        assert(output[0] == ans[0])
        assert(output[1] == ans[1])
    print("***PASSED ALL TESTS***")