# !/usr/bin/python
# Algorithms
# @Author: Kortez
# @Email: 595976736@qq.com

###########################
## do not edit this file ##
###########################

import sys
import time
import Fibonacci

def test_Fibonacci():
    start = time.clock()
    for i in range(33):
        a = Fibonacci.Fibonacci(i)
        b = Fibonacci.Fibonacci(i+1)
        c = Fibonacci.Fibonacci(i+2)
        assert(a + b == c)
    elapsed = 1000 * (time.clock() - start)
    print('Time elapsed %.4f milliseconds' % elapsed)
    print("***PASSED ALL TESTS***")